### ISSUE TITLE
Tarantool errors are lost if driver calls CompletableFuture.get() with timeout args

### ISSUE THREAD

**Issue by savinov** [tarantool/cartridge-java#82]
TarantoolClient.callForSingleResult() returns CompletableFuture

**get() without timeout args**: TarantoolFunctionCallException with error info from Tarantool
Caused by: TarantoolFunctionCallException: {"type":"ClientError","message":"...' ...}
        at io.tarantool.driver.api.SingleValueCallResultImpl.<init>(SingleValueCallResultImpl.java:28)
        at io.tarantool.driver.mappers.SingleValueCallResultConverter.fromValue(SingleValueCallResultConverter.java:23)
        at io.tarantool.driver.mappers.SingleValueCallResultConverter.fromValue(SingleValueCallResultConverter.java:13)
        at io.tarantool.driver.mappers.DefaultMessagePackMapper.fromValue(DefaultMessagePackMapper.java:107)
        at io.tarantool.driver.mappers.DefaultMessagePackMapper.fromValue(DefaultMessagePackMapper.java:87)
        at io.tarantool.driver.mappers.AbstractResultMapper.fromValue(AbstractResultMapper.java:27)
        at io.tarantool.driver.handlers.TarantoolResponseHandler.channelRead0(TarantoolResponseHandler.java:51)
        at io.tarantool.driver.handlers.TarantoolResponseHandler.channelRead0(TarantoolResponseHandler.java:23)

**get() with timeout args**: no error info from Tarantool
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021) ~[na:na]

**Comment by akudiyar** [comment]
I think it's logical that the TimeoutException doesn't have a `cause` since we cannot bind the previous error to timeout on the next call. What looks convenient for me is throwing the original error in case of the timeout exception and logging the timeout errors on each attempt. The attempts should not finish in case of a request timeout until the stop determined by the retry policy (with a proper callback filtering out the TimeoutException). In case if the original error is unavailable (all requests fail with TimeoutException), seems that throwing TimeoutException with a message is enough. We can make a "basic" timeout exception filtering callback (like `retryOnTimeout`.
